export const NAMECHANGE   = 'NAMECHANGE'
export const SENDUSERDATA   = 'SENDUSERDATA'
export const REQUEST_POST_BODY   = 'REQUEST_POST_BODY'
export const RESPONSE_VIEW_ALL   = 'RESPONSE_VIEW_ALL'
export const SELECTED_PROFILE   = 'SELECTED_PROFILE'

